name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  id-token: write

jobs:
  release:
    uses: bobleesj/release-scripts/.github/workflows/_build-wheel-release-publish.yml@v0
    with:
      project: cifkit