name: Release (GitHub/PyPI)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    uses: bobleesj/release-scripts/.github/workflows/_build-wheel-release-upload.yml@v0
    with:
      project: cifkit
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
