name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '*' 
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  pypi-publish:
    needs: [dist]
    environment:
      name: testpypi
      url: https://test/pypi.org/p/cifkit
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      # Upload to PyPI
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
      
  update-changelog:
    needs: [dist, pypi-publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run specific script for non-RC tags
        if: "!contains(github.ref, 'rc')"
        run: |
          python .github/workflows/news-changelog.py
      - name: Commit and push if there are changes
        run: |
          git add -A
          git commit -m "Update changelog"
          git push origin HEAD:${{ github.ref }}

          
      # - name: Run specific script for RC tags
      #   if: contains(github.ref, 'rc')
      #   run: |
      #     echo "Running RC-specific script..."
      #     ./scripts/rc-specific-script.sh