name: Build Wheels, Update Changelog, and Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - '*' 
permissions:
  contents: write
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: hynek/build-and-inspect-python-package@v2

  update-changelog:
    needs: [build-package]
    if: "!contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run the changelog script for full release (no rc)
        run: python .github/workflows/news-changelog.py "${{ github.ref }}"

      - name: Automatically commit changes full release (no rc)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update changelog
          branch: pypi-build  # FIXME: change to main
  
  pypi-publish:
    needs: [build-package, update-changelog]
    environment:
      name: testpypi
      url: https://test/pypi.org/p/cifkit
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  github-pre-release:
    if: contains(github.ref, 'rc')
    runs-on: ubuntu-latest
    steps:
      - name: Create pre-release for rc versions
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          generate_release_notes: true

  github-release:
    if: "!contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Create full release 
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          
